### ISSUE TITLE
Trained models?

### ISSUE THREAD

**Issue by pltrdy** [nlpaueb/SumQE#3]
Hi,

Can you share the trained model, i.e. to reproduce result from table 1?

Thanks.
Paul

**Comment by mingzi151** [comment]
Hi,

Just wondered if you could release the trained model? Thanks.

**Comment by Essex97** [comment]
Hello, 

I am sorry for my late response. You can now find on README, further instructions on how to use the pre-trained models.

Thank you, 
Stratos
